name: "Dynamic Secret Name"
on:
  workflow_dispatch:
    inputs:
      app_name:
        description: Application Name
        type: choice
        default: app-a
        options:
          - app-a
          - app-b
jobs:
  dynamic-secret-name:
    name: ${{ github.event.inputs.app_name }}
    runs-on: ubuntu-latest
    steps:
      - name: set_env
        env:
          app_name: ${{ github.event.inputs.app_name }}
        run: |
          # Secret names can only contain alphanumeric characters ([a-z], [A-Z], [0-9]) or underscores (_). Spaces are not allowed. Must start with a letter ([a-z], [A-Z]) or underscores (_).
          echo $app_name |sed 's/-/_/g' |tr '[:lower]' '[:upper:]
          echo "set_env=$(echo $app_name |sed 's/-/_/g' |tr '[:lower]' '[:upper:]')" >> $GITHUB_ENV
          cat $GITHUB_ENV
      - name: get-secret
        env:
          secret_app: ${{ secrets[format('SECRET_{0}', env.set_env)] }}
        run: |
          echo ${{ env.set_env }}
          if [ -z $secret_app ]; then
            echo "Cannot get secret"
            exit 1
          fi
